# Generated by Django 4.1 on 2024-03-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Категория услуги')),
                ('name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('question', models.TextField(blank=True, verbose_name='Комментарий заказчика')),
                ('comment', models.TextField(verbose_name='Мои комментарии')),
                ('status', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заказ услуги',
                'verbose_name_plural': 'Заказы услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Категория услуг')),
                ('short_description', models.CharField(blank=True, max_length=250, verbose_name='Краткое описание для карточки')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Изображение')),
                ('column_1_title', models.CharField(max_length=250, verbose_name='Заголовок левой колонки')),
                ('description_column_1', models.TextField(verbose_name='Описание категории услуг - левая колонка')),
                ('column_2_title', models.CharField(max_length=250, verbose_name='Заголовок правой колонки')),
                ('description_column_2', models.TextField(verbose_name='Описание категории услуг - правая колонка')),
                ('meta_description', models.CharField(default='вписать meta description', max_length=200, verbose_name='meta description')),
                ('title', models.CharField(max_length=200, verbose_name='title для страницы')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(verbose_name='Подробное описание услуги')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.servicecategory', verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
