# Generated by Django 4.1 on 2024-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='None', upload_to='service/images/%Y/%m/%d/', verbose_name='Изображение для услуги'),
            preserve_default=False,
        ),
    ]
