# Generated by Django 4.1 on 2024-03-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='portfolio/main_photos/', verbose_name='Фото для карточки')),
                ('bottom_photo', models.ImageField(upload_to='portfolio/bottom_photos/', verbose_name='Нижнее фото')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('meta_description', models.CharField(default='вписать meta description', max_length=200, verbose_name='meta description')),
            ],
            options={
                'verbose_name': 'Пример выполненной работы',
                'verbose_name_plural': 'Примеры выполненных работ',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='portfolio/gallery_photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='portfolio.project', verbose_name='Фотография для галереи')),
            ],
        ),
    ]
